#################################################
# Virtual Karyotype workflow configuration file #
#################################################

centro:
  /home/jestabrook/analyses/simulation_workflow/resources/hg38_centro.txt

cytoband:
  /home/jestabrook/analyses/simulation_workflow/resources/cytoBand.txt

resolved_cytoband:
  /home/jestabrook/analyses/virtual_karyotype_postnatal_subset/resources/hg38_800_cytoband_updated.tsv

basedir:
  /home/jestabrook/analyses/virtual_karyotype